{% set name = "yacman" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 171e71523f64b2dddbd7a547ad2dd61bca960e9d2ec613d314c5cdc2a119525b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - attmap >=0.12.9
    - oyaml
    - python
    - pyyaml >=3.13
    - ubiquerg >=0.6.1

test:
  imports:
    - yacman

about:
  home: https://github.com/databio/yacman/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A standardized configuration object for reference genome assemblies

extra:
  recipe-maintainers:
    - stolarczyk
